### ISSUE TITLE
Work on Bookmarks API in Go

### ISSUE THREAD

**Issue by schroerbrian** [ShelterTechSF/sheltertech-go#57]
We don't have a technical specification, so part of this task is to also figure out which endpoints we need and how they should be implemented.

See https://docs.google.com/document/d/1XsgVEfRH9zn4XMQlhtqgfhaJAoL8TV8F6yNlLFa2MA4/edit#bookmark=id.qedtweia4g1e for the high level feature requirement, and https://www.figma.com/file/XUttHGa1csIpbSiurbYmjo/Case-Worker?type=design&node-id=7168-4476&mode=design&t=hcGEvgxPwD4YO79c-0 for the Figma Designs.

The main UI interactions are being able to create new bookmarks, create new folders, and reordering bookmarks within folders.

**Comment by schroerbrian** [comment]
Please feel free to break into subtasks! Joe and Abel may work on this one

**Comment by katerina-kossler** [comment]
I broke out tickets for bookmarks and folders (UI and API) #97, #102, #99, #103, #98, #100, #101, and three more in askdarcel-web repo
